server:
  port: 3002
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: single-consumer
  cloud:
    inetutils: ## 网卡设置
      ignoredInterfaces:  ## 忽略的网卡
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:  ## 优先的网段
        - 172.20
management:
  endpoints:
    web:
      exposure:
        include: "*"
      # base-path: "/monitor"
      base-path: "/actuator"